[package]
name = "nvm_collide"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
tinyvec = "1.6.0"
enum-derive-2018 = "3.0.1"
macro-attr-2018 = "3.0.0"

[dev-dependencies]
bevy = { workspace = true, features=["default"] }