[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy        = { workspace = true }
nvm_curve   = { workspace = true }
nvm_collide = { workspace = true }
nvm_str_id  = { workspace = true }

[lints]
workspace = true
